// import { Inter } from "next/font/google";
// import "./globals.css";

// const inter = Inter({ subsets: ["latin"] });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({ children }) {
//   return (
//     <html lang="en">
//       <body className={inter.className}>{children}</body>
//     </html>
//   );
// }

// "use client";

import { Provider } from "react-redux";
import store from "@/lib/store";
import { Inter } from "next/font/google";
import "./globals.css";
import ClientProvider from "@/lib/ClientProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ClientProvider>
      <html lang="en">
        <body className={inter.className}>
          {/* <Provider store={store}>
          <div className="pt-32">{children}</div>
        </Provider> */}

          <div className="pt-32">{children}</div>
        </body>
      </html>
    </ClientProvider>
  );
}
